server {
    listen 80;
    location / {
        root /usr/share/nginx/html;  # Vérifiez ce chemin
        index index.html;             # Assurez-vous que index.html est présent
        try_files $uri $uri/ =404;   # Retirez "/index.html" pour tester
    }
}
